recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_y: 0.3  # zero for a differential drive robot
  min_vel_y: -0.3
  max_vel_theta: 0.3
  min_vel_theta: 0
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2

DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1.0 # 0.2
  min_vel_x: -1.0 # -0.2

  max_vel_y: 1.0 # 0.2
  min_vel_y: -1.0 # 0.2

# The velocity when robot is moving in a straight line
  max_trans_vel:  1.0 #0.2
  min_trans_vel:  -1.0 # 0.13

  max_rot_vel: 1.0 # 1.82
  min_rot_vel: -1.0 # 0.9

  acc_lim_x: 0.1 #2.5
  acc_lim_y: 0.1 # 2.5
  acc_lim_theta: 0.1 # 2.5 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 1.0
  dwa: false

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  
  holonomic_robot: true
